device:
  name: cpu
  number: 0

dataset:
  path:
    tokenized: data/processed/tokenized
    bert_featured: data/processed/bert_featured
  serializer:
    batch_size: 2

train:
  id: null
  mode: start
  batch_size: 16
  epochs: 100
